name: Auto Pull Request to Staging

on:
  push:
    branches:
      - "new-features/*"

permissions:
  contents: write  # Dibutuhkan untuk membuat pull request

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Create pull request to staging
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: staging  # Target branch
        head: ${{ github.ref_name }}  # Source branch
        title: Merge ${{ github.ref_name }} into staging
        body: |
          This pull request was automatically created by GitHub Actions.
          Please review and merge it.
        branch: auto-pr/${{ github.ref_name }}-to-staging  # Optional: Auto-created branch name
