name: CI
on:
  pull_request:
    types:
      - closed
    branches: ["staging"]
jobs:
  readytoreview:
    name: Auto Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
      - name: Deploy via SFTP
        env:
          SFTP_USERNAME: ${{ secrets.USERNAME }}
          SFTP_PASSWORD: ${{ secrets.PASSWORD }}
          SFTP_HOST: ${{ secrets.HOST }}
        run: |
          sudo -u www-data lftp -e "
              set ssl:verify-certificate false;
              set ftp:ssl-force true;
              set sftp:auto-confirm yes;
              open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST;
              lcd ./;
              cd /var/www/html/shop/wp-content/plugins/asd-passkey-login;
              mirror --reverse --verbose --overwrite \
                --exclude '.git*' \
                --exclude 'README.md' \
                --exclude 'readme.md' \
                --exclude '.gitignore' \
                ./ ./;
              bye;
            "
