name: CI
on:
  push:
    branches:
      - staging
jobs:
  readytoreview:
    name: Auto Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
      - name: Verify lftp installation
        run: |
          command -v lftp || (echo "lftp not found! Aborting..." && exit 1)
      - name: Check Repository Files
        run: |
          ls -lah $(pwd)
      - name: Deploy via SFTP
        env:
          SFTP_USERNAME: ${{ secrets.USERNAME }}
          SFTP_PASSWORD: ${{ secrets.PASSWORD }}
          SFTP_HOST: ${{ secrets.HOST }}
        run: |
          echo "Starting SFTP deployment..."
          lftp -e "
              set ssl:verify-certificate false;
              set ftp:ssl-force true;
              set sftp:auto-confirm yes;
              open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST;
              lcd $(pwd);
              cd /var/www/html/shop/wp-content/plugins/asd-passkey-login/;
              mirror --reverse --verbose --overwrite \
                  --exclude '^\.git.*' \
                  ./ ./;
              bye;
            "
          echo "Deployment finished!OK"
      - name: Send deployment notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.zoho.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Deployment to staging Successful!
          body: Deployment to staging server was successful, ready to review.
          to: bobbykarsono@gmail.com
          from: noreply@alciasolusidigital.com
          secure: true
