name: CI
on:
  push:
    branches: [ "test" ]
jobs:
  readytoreview:
    name: Auto Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4
    
    - name: Deploy to staging
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: staging
        server: 202.10.44.62
        port: 22
        ssh_private_key: ${{ secrets.SECRET_KEY }}
        local_path: ./*
        remote_path: /var/www/html/shop/wp-content/plugins/asd-passkey-login/

           
    # - name: Deploy to Staging
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: 202.10.44.62
    #     username: staging
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     port: 22
    #     protocol: ftps
    #     local-dir: ./
    #     server-dir: /var/www/html/shop/wp-content/plugins/asd-passkey-login/
    #     exclude: |
    #         **/.git*
    #         **/.git*/**
    #         **/node_modules/**
    #         **/lost+found*
        
        
          
    # - name: Sync to staging
    #   uses: burnett01/rsync-deployments@7.0.2
    #   with:
    #     switches: -avzr --delete --exclude=".git" --include=".github" --filter=""
    #     path: /
    #     remote_path: /var/www/html/shop/wp-content/plugins/asd-passkey-login
    #     remote_host: shop.fedcm.id
    #     remote_user: root
    #     remote_key: ${{ secrets.DEPLOY_KEY }}
      
        # remote_path: ${{ secrets.STAGING_PATH }}
        # remote_host: ${{ secrets.STAGING_HOST }}
        # remote_port: ${{ secrets.STAGING_PORT }}
        # remote_user: ${{ secrets.STAGING_USER }}
        # remote_key: ${{ secrets.DEPLOY_KEY }}
      
