name: CI
on:
  push:
    branches: [ "test" ]
jobs:
  readytoreview:
    name: Auto Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4
    
    - name: web deploy anything
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 202.10.44.62
        remote-user: staging
        private-ssh-key: ${{ secrets.SECRET_KEY }}
        source-path: ./
        destination-path: /var/www/html/shop/wp-content/plugins/asd-passkey-login/
        ssh-port: 22
        rsync-options: --dry-run --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
          
