name: CI
on:
  pull_request:
    types:
      - closed
    branches: ["staging"]
jobs:
  readytoreview:
    name: Auto Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
      - name: Deploy via SFTP
        env:
          SFTP_USERNAME: ${{ secrets.USERNAME }}
          SFTP_PASSWORD: ${{ secrets.PASSWORD }}
          SFTP_HOST: ${{ secrets.HOST }}
        run: |
          lftp -e "
            set ssl:verify-certificate false;
            set ftp:ssl-force true;
            set sftp:auto-confirm yes;
            open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST;
            lcd ./;
            cd /var/www/html/shop/wp-content/plugins/asd-passkey-login;
            mirror --reverse --verbose \
              --exclude '.git*' \
              --exclude 'README.md' \
              --exclude 'readme.md' \
              --exclude '.gitignore' \
              ./ ./;
            bye;
          "

    # - name: web deploy anything
    #   uses: SamKirkland/web-deploy@v1
    #   with:
    #     target-server: 202.10.44.62
    #     remote-user: root
    #     private-ssh-key: ${{ secrets.SECRET_KEY }}
    #     source-path: ./
    #     destination-path: /var/www/html/shop/wp-content/plugins/asd-passkey-login/
    #     ssh-port: 22
    #     rsync-options: --dry-run --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore

    # - name: Deploy to Staging
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: 202.10.44.62
    #     username: staging
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     port: 22
    #     protocol: ftps
    #     local-dir: ./
    #     server-dir: /var/www/html/shop/wp-content/plugins/asd-passkey-login/
    #     exclude: |
    #         **/.git*
    #         **/.git*/**
    #         **/node_modules/**
    #         **/lost+found*

    # - name: Sync to staging
    #   uses: burnett01/rsync-deployments@7.0.2
    #   with:
    #     switches: -avzr --delete --exclude=".git" --include=".github" --filter=""
    #     path: /
    #     remote_path: /var/www/html/shop/wp-content/plugins/asd-passkey-login
    #     remote_host: shop.fedcm.id
    #     remote_user: root
    #     remote_key: ${{ secrets.DEPLOY_KEY }}

    # remote_path: ${{ secrets.STAGING_PATH }}
    # remote_host: ${{ secrets.STAGING_HOST }}
    # remote_port: ${{ secrets.STAGING_PORT }}
    # remote_user: ${{ secrets.STAGING_USER }}
    # remote_key: ${{ secrets.DEPLOY_KEY }}
